### PR TITLE
Support css animation classes mimic Vue

### LINKED ISSUE #35: Add support for passing CSS animation classes as named arguments
It would be great if we could pass our CSS animation classes as named arguments like so:
```hbs
<div
  {{css-transition
    enter="opacity-0"
    enterActive="ease-out duration-200 opacity-100"
    leave="opacity-100"
    leaveActive="opacity-0 ease-in duration-200"
  }}
>
...
</div>
```
I build many of my apps with [TailwindCSS](https://tailwindcss.com) and this would be incredibly helpful :)

### PR DESCRIPTION
**Pull request by pdud**
Fixes #35 

💥 This is a breaking change for current `ember-css-transition`💥

## Differences vs Vue

Vue: https://vuejs.org/v2/guide/transitions.html#Transition-Classes

The transition javascript hooks are slightly different, `beforeEnter`, `enter`, `afterEnter`, and `enterCancelled` etc.

## State key

It turned out that using `name` was not possible as I originally proposed and have this test pass. Seeing as we are already introducing breaking changes I opted to use the named argument `state`. _There is no equivalent in Vue._

https://github.com/peec/ember-css-transitions/blob/master/tests/integration/components/css-transition-test.js#L177

<details>
<summary>First Draft PR description</summary>

Addresses #35

This is very similar to option 2.

It’s also a breaking change for current ember-css-transition users in the exact same way for the exact same reasons.

The difference is in using positional arguments (transition name or hash) vs named arguments (name, enter, enterActive, leave, leaveActive)

</details>

<details>
<summary>Second Draft PR description</summary>

Fixes #35 

💥 This is a breaking change for current `ember-css-transition`💥

This is one step between `ember-css-transition`'s current setup and matching Vue's transitions.

## Differences vs Vue

This uses `enter` `enterActive` classes. Vue uses `enter` `enterActive` `enterTo` 
classes [(docs)](https://vuejs.org/v2/guide/transitions.html#Transition-Classes). I have a PR that mimics it more closely using the same entry points. I left it on my fork so the diff is easier to see. https://github.com/pdud/ember-css-transitions/pull/1

The transition javascript hooks are also slightly different, `beforeEnter`, `enter`, `afterEnter`, and `enterCancelled` etc.

**What are your thoughts on going all in on matching Vue?**

We could try make the breaking changes less aggressive between versions? Perhaps that helps people migrate?

- v2 this
- v3 match Vue

I could have them both ready, so those interested could go straight to v3 😅.

## Name vs State

It turned out that using `name` was not possible and have this test pass. Seeing as we are already introducing breaking changes I opted to use the named argument `state`. There is no equivalent in Vue.

https://github.com/peec/ember-css-transitions/blob/master/tests/integration/components/css-transition-test.js#L177

### Outstanding

- [x] Support #33 w/ booleans (rebased to support merged PR)

</details>

### CODE REVIEW

**Comment by miguelcobain** [comment]
@pdud I think that this version wins for its API.
It would be great if we could support #33 on this PR, perhaps using the enter/exit booleans as in the react version. I thin that way we would have the best of both worlds.

Do you need anything from me?
Thank you for your time and sorry for delay in reviewing the PRs!

**Comment by pdud** [comment]
Perfect, I'll get this one in shape for review! I'll include something for #33 too :)

I should be good for now and will reach out if I need anything :) No worries, thank you so much!

**Comment by pdud** [comment]
hi @miguelcobain ready for a review! I've left some comments above in the updated PR description. 

Let me know what you think! I'm happy to make changes!

Thank you!

**Comment by pdud** [comment]
hey @miguelcobain friendly bump :)

**Comment by miguelcobain** [comment]
@pdud master has now some exciting bugfixes from #39 

could you please rebase this PR?

**Comment by pdud** [comment]
Love it! #39 worked well for me and fixed any issues I was seeing (from the addon doc pages).

I wanted to point out the Differences vs Vue section in my PR description here: https://github.com/peec/ember-css-transitions/pull/38#issue-422317346

Happy to make any changes! Thanks

**Comment by miguelcobain** [comment]
> This uses enter enterActive classes. Vue uses enter enterActive enterTo
classes (docs). I have a PR that mimics it more closely using the same entry points. I left it on my fork so the diff is easier to see. pdud#1

@pdud so you basically have the support for `enterTo` on that branch? If it already there, I don't see a reason to not bring that into this PR as well.

**Comment by pdud** [comment]
Sounds good! I'll do that now 👍

**Comment by pdud** [comment]
@miguelcobain ready for you 🎉 😄

**Comment by pdud** [comment]
Hey @miguelcobain - I know you’re super busy. Can I have another review? 😇😇

**Comment by miguelcobain** [comment]
@pdud The way the `state` is right now doesn't make a lot of sense to me.

Previously you could have multiple class add/removal animations because you could pass in an arbitrary number of named arguments.

We can keep that behavior even with this "vue-like" version.
However, I'm considering **removing support for class add/removals entirely**. Only ngAnimate supports that (and that's an old version for angular 1). There must be a good reason react and vue didn't need to support that.

In practice I think most class add/removals can be handled by adding/removing the class itself. It's the insert/destroy part of the addon that is indeed more complicated to do in user land.

Another thing that I think we're in a good position to tackle now is to have the `@duration` argument (#18). This argument allows you to override the duration of the transition explicitly.

Example:
- `@duration={{1000}}`
- `@duration={{hash enter=500 leave=800}}`

Please let me know your thoughts.

**Comment by pdud** [comment]
@miguelcobain 

Ah, I see. Yes, I should have realized that was the case. I suppose one could add multiple `{{css-transition state=…}}` as is.

I also agree that the insert/ destroy bit is the more complicated bit. Perhaps in ember-css-transition’s early days add/ remove was of more value. I’m personally interested in insert/ destroy and like you said will probably handle add-remove via the class directly.

Yes duration is certainly something we can address! I like the API you suggested. It seems right in line with Vue. In an effort to get this PR in as soon as possible I could fast follow with that :) If it’s needed now I can also do that!

Thank you!

**Comment by miguelcobain** [comment]
I can do that myself, no worries. I'm just a bit worried about removing the add/removal feature of the addon. If React and Vue can get away with not having it, I guess we can too, right?

Another thing I'd like to have is some sort of migration guide for people with old styles. But his is documentation related and could be addressed separately.

**Comment by pdud** [comment]
Yes I would agree if React and Vue both do not have it they must not see the value.

If there is kick back from users can we reconsider? Perhaps even a second modifier if needed.

**Comment by miguelcobain** [comment]
> If there is kick back from users can we reconsider? Perhaps even a second modifier if needed.

Since we will major bump, users can stay in the previous version.
If someone comes across a real use case that can't be done with a simple `{{if`, I think we can add that feature back somehow.

**Comment by pdud** [comment]
Ah true! That sounds like it will work well.

**Comment by pdud** [comment]
hey @miguelcobain! I know you must be busy! Anything I can do to help get this over the finish line?

**Comment by miguelcobain** [comment]
@pdud `2.0.0` was published. Thanks a lot for championing this feature and I'm sorry for the delay.
I ended up doing some cleanup and reworking a lot of the documentation to make sure users catch up easily with the changes.

Thanks!

**Comment by pdud** [comment]
@miguelcobain Thank you so much! The changes to the docs look great! 👍

**Comment by roomman** [comment]
@pdud thanks for this PR it's exactly what I've been looking for. @miguelcobain, one comment about the readme / documentation: I'm using Tailwind and it wasn't immediately obvious that you need to pass in an array of utility classes (eg `enterClass=(array "duration-200" "ease-in" "opacity-0"`). Is it worth a PR to add an example using utility classes, or would you advise me to stick to CSS components when using this addon? Many thanks.

**Comment by miguelcobain** [comment]
@roomman if that's the case, then it is a bug. You should be able to pass in things like `enterClass="duration-200 ease-in epacity-0"`.

**Comment by pdud** [comment]
hey @roomman 

As @miguelcobain said you can pass in the Tailwind utility classes as a string that is separated by spaces. For example rather than `enterClass=(array "duration-200" "ease-in" "opacity-0")` you would do `enterClass="duration-200 ease-in opacity-0"`.

**note:** you want to put `duration` and `ease-in` in enterActiveClass

For example for Tailwind you would do

```
enterClass="opacity-0"
enterActiveClass="duration-200 ease-in"
enterToClass="opacity-100"
```

Does that help?

-----------------------

@miguelcobain 

I think there is two things we can do

1. We should update the doc site when possible to 2.0.0

2. We should demo passing in an array (a string separated by spaces.
) on the readme. I'll put in a little PR for your consideration.

**Comment by miguelcobain** [comment]
I forgot I had to manually update the docs site. I just did. 👍 
Thanks.

**Comment by roomman** [comment]
@pdud and @miguelcobain, not sure what I got wrong this morning but it's working as expected, and as per the new docs. Many thanks 👍

**Pull request merged**
