### PR TITLE
Upgrade ember-modifier to v2

### PR DESCRIPTION
**Pull request by SergeAstapov**

### CODE REVIEW

**Comment by miguelcobain** [comment]
Thanks. 👍

**Comment by SergeAstapov** [comment]
@miguelcobain do you think v2.1.0 could be released with this update?

**Comment by miguelcobain** [comment]
@SergeAstapov sure. Just curious, why exactly do you need this update?

**Comment by miguelcobain** [comment]
`2.1.0` was released

**Comment by SergeAstapov** [comment]
Thank you @miguelcobain!

This allows to upgrade `ember-modifier` package in our app (as [app and all dependencies should use same version](https://github.com/salsify/ember-cli-dependency-lint#motivation)) and benefit from [all enhancements introduced in v2](https://github.com/ember-modifier/ember-modifier/releases/tag/v2.0.0) of ember-modifier package.

**Pull request merged**
