### PR TITLE
Remove ember-cli-requestanimationframe-polyfill

### PR DESCRIPTION
**Pull request by nlfurniss**
This addon targets IE 10 as it's oldest browser, which [supports rAF natively](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame#browser_compatibility), so I believe this polyfill is not necessary.

### CODE REVIEW

**Comment by miguelcobain** [comment]
@nlfurniss that addon should only import the polyfill if you have a browser in your `targets.json` that doesn't support raf.
So this shouldn't be affecting you in any way. Was there a particular reason for wanting to remove it?

**Comment by nlfurniss** [comment]
It’s using an outdated version of ember-cli-Babel (v6), and since it seemed like it wasn’t needed, I figured it was easier to remove it than bump its dep and then then bump it in this addon.

**Comment by nlfurniss** [comment]
@miguelcobain do you mind cutting a new release?

**Comment by miguelcobain** [comment]
@nlfurniss released on `2.1.1`

**Comment by nlfurniss** [comment]
> @nlfurniss released on `2.1.1`

Thank you!

**Pull request merged**
